version: '2'
services:
  mongo:
    image: mongo:3.3
    container_name: mongo
    hostname: mongo
    ports: 
      - "27017:27017"
  widestage:
    build: .
    image: jonbrouse/widestage
    container_name: widestage
    hostname: widestage
    volumes:
      - ./server.js:/srv/app/server.js
      - ./server/config/config.js:/srv/app/server/config/config.js
    links:
      - mongo
    environment:
      - IP=0.0.0.0
      - MONGOHOST=mongo
      #- PORT=8080
    ports: 
      - "80:80"
      - "8080:8080"
      - "8081:8081"
